config/routes.rb
Sms::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :messages do
        post :set_status, on: :collection
        get :send_message, on: :collection
        get :restart, on: :member
      end
      resources :assets
      resources :contacts do
        get :add, on: :collection
        get :del, on: :collection
      end
      resources :groups do
        post :clear, on: :member
      end
    end
  end

  namespace :admin do
    resources :users
    root to: "users#index"
  end
  get '/pages/:id' => 'pages#show'
  get '/templates/:controller_name/:id' => "templates#show"

  get 'switch_user' => 'switch_user#set_current_user'

  root to: "application#index"
end

app/models/user.rb
# -*- encoding: utf-8 -*-
class User < ActiveRecord::Base
  store_accessor :settings, :language, :sender, :contract

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_access_token

  has_many :contacts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :assets, dependent: :destroy

  after_create :create_main_group

  def create_main_group
    self.groups.create(name: 'All contacts', editable: false)
  end

  def main_group
    self.groups.find_by_editable(false)
  end

  # role model
  validates_presence_of :role

  def role_symbols
    user_role = self.role
    if user_role then [user_role.to_sym] else [:guest] end
  end

  def user_role
    roles = {"admin" => "Administrator", "user" => "User", "moderator" => "Moderator"}
    roles[self.role]
  end

  def charge(amount)
    raise NotEnoughSms if amount > self.sms_amount
    self.decrement!(:sms_amount, amount)
  end

  class NotEnoughSms < StandardError; end

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/controllers/admin/users_controller.rb
# --- encoding: utf-8 ---
class Admin::UsersController < Admin::BaseController

  before_filter :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order(:created_at)
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, flash: {success: "User successfully removed."}
  end

  def edit
  end

  def new
    @user = User.new
  end

  def update
    parameters = user_params
    if user_params[:password].blank?
      parameters.delete(:password)
      parameters.delete(:password_confirmation)
    end
    @user.update_attributes(parameters)
    redirect_to admin_users_path, flash: { success: "User #{@user.email} successfully updated." }
  end

  def create
    parameters = user_params
    @user = User.new(parameters)
    if @user.save
      redirect_to admin_users_path, flash: { success: "User #{@user.email} successfully updated." }
    else
      render :new
    end
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role, :sms_amount, :sender, :contract)
    end
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user], html: {autocomplete: 'off'} do |f|
  .form-group
    = f.label :email, "Email"
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, "Password"
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, "Confirm password"
    = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    = f.label :sms_amount, "SMS Balance"
    = f.text_field :sms_amount, class: 'form-control'
  .form-group
    = f.label :sender, "Sender"
    = f.text_field :sender, class: 'form-control'
  .form-group
    = f.label :contract, "Contract"
    = f.select :contract, options_for_select([['Обычный', 'default'], ['Прямой', 'alpha']], @user.contract)
  .form-group
    = f.label :role, "Role"
    = f.select :role, [["Administrator", "admin"], ["User", "user"]], {include_blank: false}, class: 'form-control'
  = f.submit "Save"

app/views/admin/users/edit.html.haml
= render 'form'

app/views/admin/users/index.html.haml
= link_to "New user", new_admin_user_path, class: 'btn btn-default'

%table.table
  %tr
    %th Email
    %th Role
    %th Actions
  - @users.each do |user|
    %tr(id="user_#{user.id}")
      %td= user.email
      %td= user.user_role
      %td
        = link_to "Remove", admin_user_path(user), method: :delete, remote: true
        = link_to "Update", edit_admin_user_path(user)
        = link_to "Become", "/switch_user?scope_identifier=user_#{user.id}"

app/views/admin/users/new.html.haml
= render 'form'