config/routes.rb
Sms::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :messages do
        post :set_status, on: :collection
        get :send_message, on: :collection
        get :restart, on: :member
      end
      resources :assets
      resources :contacts do
        get :add, on: :collection
        get :del, on: :collection
      end
      resources :groups do
        post :clear, on: :member
      end
    end
  end

  namespace :admin do
    resources :users
    root to: "users#index"
  end
  get '/pages/:id' => 'pages#show'
  get '/templates/:controller_name/:id' => "templates#show"

  get 'switch_user' => 'switch_user#set_current_user'

  root to: "application#index"
end

app/controllers/application_controller.rb
# --- encoding: utf-8 ---
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  filter_access_to :all unless Rails.env == 'test'

  before_action :authenticate_user!
  before_action :set_locale
  before_action :set_gon_current_user

  protect_from_forgery

  def set_locale
    I18n.locale = get_locale()
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

  def get_locale
    if current_user && available_languages.include?(current_user.language)
      current_user.language
    elsif accept_lang = request.env['HTTP_ACCEPT_LANGUAGE']
      lang = accept_lang.scan(/^[a-z]{2}/).first
      lang if available_languages.include?(lang)
    else
      params[:locale] || :ru
    end
  end

  def available_languages
    ['ru', 'en']
  end

  def set_gon_current_user
    gon.current_user = {id: current_user.id, access_token: current_user.access_token, email: current_user.email, balance: current_user.sms_amount} if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top(role="navigation")
  .container
    .navbar-header
      %button.navbar-toggle(type="button" data-toggle="collapse" data-target="#nav-collapse")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand(href="/") Sms
    #nav-collapse.collapse.navbar-collapse
      - if signed_in?
        %ul.nav.navbar-nav
          %li(ng-class="{active: state.current.data.feature == 'messages'}")
            %a(ui-sref='messages')
              %i.icon-document
              Messages
          %li(ng-class="{active: state.current.data.feature == 'contacts'}")
            %a(ui-sref='contacts.list')
              %i.icon-document
              Contacts
          %li(ng-class="{active: state.current.data.feature == 'documentation'}")
            %a(ui-sref='documentation.contents')
              %i.icon-document
              API
      - if signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            %a
              Balance:
              {{user.balance}} SMS
          %li.dropdown
            = link_to current_user.email, "#", class: "dropdown-toggle", "data-toggle" => "dropdown"
            %ul.dropdown-menu
              - if permitted_to? :manage, :admin_users
                %li= link_to "Settings", admin_root_path
              %li= link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign in", new_user_session_path

app/views/application/_page_header.html.haml
.page-header
  %h1= title

app/views/application/index.html.haml
%alert(ng-repeat="alert in alerts" type="{{alert.type}}" close="closeAlert($index)") {{alert.msg}}
%div(ui-view)